using UnityEngine;
using System.Collections;
using System;

public class InformationSheet : MonoBehaviour {
	string[] questions = new string[11];
	string[] answers = new string[11];
	//Texture info1 = new Texture();
	//Texture info2 = new Texture();
	public Texture2D infoSheet1;
	public Texture2D infoSheet2;
	public Texture2D infoSheet3;



	/*



 





 

 

 

 

 

Daniel Ingrey 
Email: di31@sussex.ac.uk 

If you have concerns about the way in which this research is being undertaken 
please contact my supervisor: Alice Eldridge 
Email: alicee@sussex.ac.uk 
 
Thank you for taking part in this study."*/

	/*void OnGUI () {
		/*if (GUI.Button (new Rect (10,10,150,100), "I am a button")) {
			print ("You clicked the button!");
		}
		GUILayout.BeginArea(new Rect(Screen.width / 2 - 150, Screen.height /2 - 150, 300, 300));
		GUILayout.Label ("example string\nyo this is the next line\nnext line\nnext line" +
		                 "\nnext line\nnext line\nnext line");
		//GUILayout.Button("Click me");
		//GUILayout.Button("Or me");
		GUILayout.EndArea();

	}*/
	/*
	public Vector2 scrollPosition;
	public string longString = "This is a long-ish string";
	void OnGUI() {
		GUILayout.BeginArea(new Rect(Screen.width / 2 - 150, Screen.height - 150, 300, Screen.height-300));
		scrollPosition = GUILayout.BeginScrollView(scrollPosition, GUILayout.Width(300), GUILayout.Height(100));
		GUILayout.Label(longString);
		if (GUILayout.Button("Clear"))
			longString = "";
		
		GUILayout.EndScrollView();
		if (GUILayout.Button("Add More Text"))
			longString += "\nHere is another line";
		GUILayout.EndArea();
		
	}*/
	public Vector2 scrollPosition = Vector2.zero;
	void OnGUI() {

		string title = "Procedural Generation of Interactive Environments using Biologically Inspired Computation";
		
		string info = "You are being invited to take part in a research study. Before deciding if you would like to take part, " +
						"it is important for you to understand what the research will involve, " +
					"and why it is being undertaken. Please take time to read the following information carefully.";
			
		questions[0] = "What is the purpose of the study? ";
			answers[0] = "The study aims to research the use of biologically inspired computation* in the role of " + 
						 "procedural content generation(PCG)** within videogames and interactive environments. The " + 
						 "study should take no longer than 20 minutes. You will be presented with two versions of a " + 
						 "game in first-person perspective, each to be played one after the other. The gameplay " + 
						 "elements and overall design will be the same between both versions but each will have been " + 
						 "created using different PCG techniques.\n" + 
						 "*programming methods that model life\n" + 
						 "**content generated by algorithms, rather than manually"; 

		questions[1] = "Why have I been invited to participate?";
		answers[1] = 	"You are someone that has some experience of, or interest in, videogames/interactive " +
						"environments. Approximately 20 other people will be taking this study.";

		questions[2] = "Do I have to take part?"; 
		answers[2] = "Taking part in this study is entirely voluntary. If you do decide to take part, you will be asked " +
					"to click to accept or deny on a digital consent form. You are free to withdraw from the study " + 
					"at any time without needing to give a reason. If you are a student, taking part in this study " +
					"will have no impact on your marks, assessment, or future study."; 

		questions[3] = "What will happen to me if I take part?";
		answers[3] = "After playing the game you will be asked to complete a short online questionnaire " +
					"about your experiences with the two versions of the game, and how you felt they " +
					"compared. You will also be asked to provide your age within a range, your gender, " +
					"and the types of game you play, if any. Additional data may also be collected " +
					"automatically about how long it took you to play and whether you quit before the end " +
					"of the play session."; 

		questions[4] = "What are the possible disadvantages of taking part?";
		answers[4] = "The time involved taken in this study will vary depending on your previous " +
				"experience with games, and possible bugs that may appear that force you to quit " +
				"before the game ends.";

		questions[5] = "What are the possible benefits of taking part?";
		answers[5] = "The game is designed to be entertaining for the participants of the study. It is hoped " +
				"your feedback will be of use for future development of games using these " +
				"techniques.";

		questions[6] = "Will my information in this study be kept confidential?";
		answers[6] = "The data collected will be kept strictly confidential. Your anonymity will be ensured " +
			"as you will not have to provide your name, and the age you give will be within a range.";

		questions[7] = "What should I do if I want to take part?"; 
		answers[7] = "Please press accept to continue."; 

		questions[8] = "What will happen to the results of the research study?"; 
		answers[8] = "The results will be used in my third year project BSc Thesis. Should you wish to obtain a " +
			"copy of the thesis, please contact me via the details listed in the contact section.";

		questions[9] = "Who is organising and funding the research?"; 
		answers[9] = "This research is being conducted by myself, a student of Informatics at the University of Sussex.";

		questions[10] = "Who has approved this study?"; 
		answers[10] = "Prof Peter Cheng, School of Engineering and Informatics, University of Sussex.";

		string conTitle = "Contact for Further Information"; 

		string conDetails = "Daniel Ingrey\n" +
			"Email: di31@sussex.ac.uk";

		string concerns = "If you have concerns about the way in which this research is being undertaken " +
				"please contact my supervisor: Alice Eldridge\n" + 
				"Email: alicee@sussex.ac.uk ";

		string thanks = "Thank you for taking part in this study.";
		// Make a group on the center of the screen


		GUI.BeginGroup (new Rect (Screen.width / 2 - 400, Screen.height / 2 - 400, 800, 800));
		// All rectangles are now adjusted to the group. (0,0) is the topleft corner of the group.
		
		// We'll make a box so you can see where the group is on-screen.
		GUI.Box (new Rect (0,0,800,800),"");
		scrollPosition = GUI.BeginScrollView(new Rect(0, 0, 800, 797), scrollPosition, new Rect(0, 3, 700, 2500),false,true);
		//GUI.Box (new Rect (10,100,770,2390),"");
		//string stringToEdit = "Hello World";
		//GUI.skin.textField.wordWrap = true;
		//GUI.skin.textField.stretchHeight = true;
		//GUI.skin.textField.fontSize = 15;
		//Rect infoSheet1 = new Rect(10,150,infoSheet1.width,infoSheet1.Length);
		GUI.Label(new Rect(150,10,infoSheet1.width,infoSheet1.height), infoSheet1);
		//Rect infoSheet2 = new Rect(10,150,infoSheet1.width,infoSheet1.height);
		GUI.Label(new Rect(150,infoSheet1.height,infoSheet2.width,infoSheet2.height), infoSheet2);
		GUI.Label(new Rect(150,infoSheet1.height*2-10,infoSheet2.width,infoSheet2.height), infoSheet3);
		//int anCnt = 0;
		//int qCnt = 0;
		/*for(int i = 0; i < 11; i ++){
			GUI.skin.textField.fontSize = 20;
			questions[i] = GUI.TextField(new Rect(10, qCnt + 160, 760, 30), questions[i], questions[i].Length);
			GUI.skin.textField.fontSize = 15;
			answers[i] = GUI.TextField(new Rect(10, anCnt + 190, 760, 125), answers[i], answers[i].Length);
			anCnt += 170;
			qCnt += 170;
		}
		for(int i = 0; i < 11; i ++){
			GUI.Label(infoSheet, questions[i]);
			GUI.skin.textField.fontSize = 15;
			GUI.Label(infoSheet, answers[i]);
			anCnt += 170;
			qCnt += 170;
		}*/

		GUI.EndScrollView();

		//GUI.Button (new Rect (375,10,50,50), "Click me");
		
		// End the group we started above. This is very important to remember!
		GUI.EndGroup ();

		/*scrollPosition = GUI.BeginScrollView(new Rect(10, 300, 800, 800), scrollPosition, new Rect(0, 0, 800, 800),false,true);
		GUI.Button(new Rect(0, 0, 100, 20), "Top-left");
		GUI.Button(new Rect(120, 0, 100, 20), "Top-right");
		GUI.Button(new Rect(0, 180, 100, 20), "Bottom-left");
		GUI.Button(new Rect(120, 180, 100, 20), "Bottom-right");
		GUI.EndScrollView();*/
	}

	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
	
	}
}
